name: CI

on:
  pull_request:
  push:
    branches: [ main, next ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: true

      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Format check
        run: |
          diff_files=$(go fmt ./...)
          if [ -n "$diff_files" ]; then
            echo "Unformatted files:" && echo "$diff_files" && exit 1
          fi

      - name: Vet
        run: go vet ./...

      - name: Build
        run: go build ./...

      - name: Test
        run: go test -race -coverprofile coverage.out ./...

      - name: Coverage HTML
        run: go tool cover -html=coverage.out -o coverage.html

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.html

