name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main, next ]

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            code:
              - '**/*.go'
              - 'go.mod'
              - 'go.sum'
              - 'cmd/**'
              - 'internal/**'
            docs:
              - '**/*.md'
              - 'docs/**'
              - 'resources/samples/**'

      - name: Summary
        run: |
          echo "code changes: ${{ steps.changes.outputs.code }}" >> $GITHUB_STEP_SUMMARY
          if [ "${{ steps.changes.outputs.code }}" != "true" ]; then
            echo "Docs-only or non-code change detected; skipping heavy steps." >> $GITHUB_STEP_SUMMARY
          fi

      - name: Setup Go
        if: steps.changes.outputs.code == 'true'
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: true

      - name: Install ffmpeg
        if: steps.changes.outputs.code == 'true'
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Format check
        if: steps.changes.outputs.code == 'true'
        run: |
          diff_files=$(go fmt ./...)
          if [ -n "$diff_files" ]; then
            echo "Unformatted files:" && echo "$diff_files" && exit 1
          fi

      - name: Vet
        if: steps.changes.outputs.code == 'true'
        run: go vet ./...

      - name: Build
        if: steps.changes.outputs.code == 'true'
        run: go build ./...

      - name: Test
        if: steps.changes.outputs.code == 'true'
        run: go test -race -coverprofile coverage.out ./...

      - name: Coverage HTML
        if: steps.changes.outputs.code == 'true'
        run: go tool cover -html=coverage.out -o coverage.html

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        if: steps.changes.outputs.code == 'true'
        with:
          name: coverage
          path: coverage.html
