name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main, next ]

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            code:
              - '**/*.go'
              - 'go.mod'
              - 'go.sum'
              - 'cmd/**'
              - 'internal/**'
            docs:
              - '**/*.md'
              - 'docs/**'
            samples:
              - 'resources/samples/**'
            workflows:
              - '.github/workflows/**'

      - name: Summary
        run: |
          echo "code:      ${{ steps.changes.outputs.code }}" >> $GITHUB_STEP_SUMMARY
          echo "docs:      ${{ steps.changes.outputs.docs }}" >> $GITHUB_STEP_SUMMARY
          echo "samples:   ${{ steps.changes.outputs.samples }}" >> $GITHUB_STEP_SUMMARY
          echo "workflows: ${{ steps.changes.outputs.workflows }}" >> $GITHUB_STEP_SUMMARY
          if [ "${{ steps.changes.outputs.code }}" != "true" ] && [ "${{ steps.changes.outputs.samples }}" != "true" ] && [ "${{ steps.changes.outputs.workflows }}" != "true" ]; then
            echo "Docs-only or non-executable change detected; skipping heavy steps." >> $GITHUB_STEP_SUMMARY
          fi

      - name: Setup Go
        if: steps.changes.outputs.code == 'true' || steps.changes.outputs.samples == 'true' || steps.changes.outputs.workflows == 'true'
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          cache: true

      - name: Setup ffmpeg
        if: steps.changes.outputs.code == 'true' || steps.changes.outputs.samples == 'true' || steps.changes.outputs.workflows == 'true'
        uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          ffmpeg-version: '6.0'

      - name: Format check
        if: steps.changes.outputs.code == 'true' || steps.changes.outputs.samples == 'true' || steps.changes.outputs.workflows == 'true'
        run: |
          diff_files=$(go fmt ./...)
          if [ -n "$diff_files" ]; then
            echo "Unformatted files:" && echo "$diff_files" && exit 1
          fi

      - name: Vet
        if: steps.changes.outputs.code == 'true' || steps.changes.outputs.samples == 'true' || steps.changes.outputs.workflows == 'true'
        run: go vet ./...

      - name: Build
        if: steps.changes.outputs.code == 'true' || steps.changes.outputs.samples == 'true' || steps.changes.outputs.workflows == 'true'
        run: go build ./...

      - name: Build CLI binary

        if: steps.changes.outputs.code == 'true' || steps.changes.outputs.samples == 'true' || steps.changes.outputs.workflows == 'true'
        run: go build -v -o bin/video-lightning-detector .

      - name: Test
        if: steps.changes.outputs.code == 'true' || steps.changes.outputs.samples == 'true' || steps.changes.outputs.workflows == 'true'
        run: go test -race -coverprofile coverage.out ./...

      - name: Coverage HTML
        if: steps.changes.outputs.code == 'true' || steps.changes.outputs.samples == 'true' || steps.changes.outputs.workflows == 'true'
        run: go tool cover -html=coverage.out -o coverage.html

      - name: Upload coverage
        uses: actions/upload-artifact@v4
        if: steps.changes.outputs.code == 'true' || steps.changes.outputs.samples == 'true' || steps.changes.outputs.workflows == 'true'
        with:
          name: coverage
          path: coverage.html

      

      - name: Functional assertions (positive and negative)
        if: steps.changes.outputs.code == 'true' || steps.changes.outputs.samples == 'true' || steps.changes.outputs.workflows == 'true'
        run: |
          set -euo pipefail

          POSITIVE="resources/samples/sample_yes.mp4"
          NEGATIVE="resources/samples/sample_no.mp4"

          if [ ! -f "$POSITIVE" ] || [ ! -f "$NEGATIVE" ]; then
            echo "Skipping functional assertions (samples missing)." | tee -a $GITHUB_STEP_SUMMARY
            exit 0
          fi

          # Positive: expect >0 detections
          ./bin/video-lightning-detector -i "$POSITIVE" -o ./runs/ci-positive -a -s 0.1 -f | tee positive.log
          POS_COUNT=$(grep -c 'Frame meets the threshold requirements\.' positive.log || true)
          if [ -z "${POS_COUNT:-}" ] || [ "$POS_COUNT" -le 0 ]; then
            echo "Expected >0 detections on positive sample; got ${POS_COUNT:-unset}" | tee -a $GITHUB_STEP_SUMMARY
            exit 1
          fi

          # Negative: expect 0 detections
          ./bin/video-lightning-detector -i "$NEGATIVE" -o ./runs/ci-negative -a -s 0.1 -f | tee negative.log
          NEG_COUNT=$(grep -c 'Frame meets the threshold requirements\.' negative.log || true)
          if [ -z "${NEG_COUNT:-}" ]; then
            echo "Could not parse detection count on negative sample" | tee -a $GITHUB_STEP_SUMMARY
            exit 1
          fi
          if [ "$NEG_COUNT" -ne 0 ]; then
            echo "Expected 0 detections on negative sample; got $NEG_COUNT" | tee -a $GITHUB_STEP_SUMMARY
            exit 1
          fi

          echo "✅ Functional assertions passed: positive=$POS_COUNT negative=$NEG_COUNT" >> $GITHUB_STEP_SUMMARY
